services:
  backend:
    build: .
    container_name: vafund-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./crypto:/app/crypto
    restart: unless-stopped
    networks:
      - fabric_test

networks:
  fabric_test:
    external: true
